### ISSUE TITLE
Cannot join a multiplayer room while already in one exception

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11315]
**Describe the bug:** Just enter a room, quickly quit the screen, and then enter ~the same~ another room.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/35318437/103143617-d07d1e00-46ce-11eb-84b6-a3909af5243d.mp4

**osu!lazer version:** 2020.1225.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5742537/runtime.log)

**Comment by peppy** [comment]
Out of curiosity, can you join if you wait a while after triggering this? And in this scenario, can you see yourself in the participants (avatars) list to the right even though you left?

**Comment by Joehuu** [comment]
Nah, can't join after waiting a while (it's indefinite), and my avatar stays there until attempting to join, getting an exception, and it disappearing.

Can see my avatar in the video.
![chrome_MKJfYgiHgf](https://user-images.githubusercontent.com/35318437/103144089-56ea2d80-46d8-11eb-91a3-b4c5a03794b4.jpg)

**Comment by peppy** [comment]
This has been resolved server-side.

**Comment by Joehuu** [comment]
Can still reproduce, although it's not 100% reproducible like before.

[runtime.log](https://github.com/ppy/osu/files/5833347/runtime.log)

https://user-images.githubusercontent.com/35318437/104981924-6a7a7280-59be-11eb-830f-f826a7c1bf56.mp4

**Comment by peppy** [comment]
Relvant issues (both are likely separate):

```
2021-01-19 02:50:49 [error]: System.InvalidOperationException: This bindable has already been Returned.
2021-01-19 02:50:49 [error]: at osu.Framework.Bindables.LeasedBindable`1.Return()
2021-01-19 02:50:49 [error]: at osu.Game.Screens.OnlinePlay.OngoingOperationTracker.endOperation()
2021-01-19 02:50:49 [error]: at osu.Framework.Threading.Scheduler.Add(Action task, Boolean forceScheduled)
2021-01-19 02:50:49 [error]: at osu.Game.Screens.OnlinePlay.OngoingOperationTracker.<BeginOperation>b__5_0()
2021-01-19 02:50:49 [error]: at osu.Game.Screens.OnlinePlay.Lounge.LoungeSubScreen.<>c__DisplayClass34_0.<joinRequested>b__0(Room r)
2021-01-19 02:50:49 [error]: at osu.Game.Screens.OnlinePlay.Multiplayer.MultiplayerRoomManager.<>c__DisplayClass13_0.<joinMultiplayerRoom>b__1()
2021-01-19 02:50:49 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
```

```
2021-01-19 02:51:19 [error]: Failed to join multiplayer room.
2021-01-19 02:51:19 [error]: System.AggregateException: One or more errors occurred. (Cannot join a multiplayer room while already in one.)
2021-01-19 02:51:19 [error]: ---> System.InvalidOperationException: Cannot join a multiplayer room while already in one.
2021-01-19 02:51:19 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.JoinRoom(Room room)
2021-01-19 02:51:19 [error]: --- End of inner exception stack trace ---
```

**Comment by peppy** [comment]
The `OngoingOperationTracker` looks to be this scenario:

- The `OngoingOperationTracker` instance itself is disposed, which causes `UnbindAllBindables` to be triggered, returning the internal leased bindable.
- At a later point, the `IDisposable` from the `BeginOperation` call is disposed, causing a second return operation.

Resolution may be do null the leased bindable on disposal, or do ensure all cases of returning (ending) the operation are scheduled to the same component which owns the ongoing tracker.
