### ISSUE TITLE
"Disable Windows key during gameplay" not working

### ISSUE THREAD

**Issue by kitkatsim** [ppy/osu#11450]
"Disable Windows key during gameplay" option is not working. Toggling the setting on and off makes no difference.

https://user-images.githubusercontent.com/37004012/104086569-1bcd2a00-5294-11eb-8484-8809adda4f64.mp4
the video recording shows a black screen pause when windows key is pressed, but it's actually instant

version 2021.109.0

**Comment by Game4all** [comment]
Are you by any chance launching the game with --tk in launch arguments? If that's the case removing it from the launch arguments to use the SDL2 (default) backend should fix it, as the OpenTK backend (`--tk`) doesn't play nice with the window hooks used to disable the key.

**Comment by Joehuu** [comment]
This has something to do with raw input. If it's already enabled or enabled in a session, this breaks until restarting (i.e. disabling will not work until restarting).

**Comment by peppy** [comment]
Even after a restart, I still can't get the windows key to disable when raw input is enabled.
