### ISSUE TITLE
Win + g prevents from using hotkeys

### ISSUE THREAD

**Issue by Layendan** [ppy/osu#11489]
**Describe the bug:** 
If using `Windows` + `g` to open the Xbox Game Bar while in the game, keys (such as `Escape` to go back, `Space` to go forwards... will not work)

Note: key tapping still works during songs, but hitting the `Space` key to skip will not work.

Switching windows and back (`Alt` + `Tab`ing or clicking another app and clicking back on Osu!) fixes the problem.

**Screenshots or videos showing encountered issue:** 
[Video](https://user-images.githubusercontent.com/46062388/104666049-26bafc80-5690-11eb-81be-d3e5f4c1b860.mp4)

**osu!lazer version:** 
osu 2021.109.0.0
(issue since late 2019/early 2020 might have been since longer though)

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5817724/logs.zip)

**Comment by Gabixel** [comment]
Duplicate of https://github.com/ppy/osu-framework/issues/2198 (my video is missing, I will try to reupload it as soon as possible).

I remember it was fixed in `SDL` when I last tested it, but for some reason, it seems to have regressed.

**Comment by peppy** [comment]
As a note, this may be fixed with the next framework bump, assuming it only happens when raw input is enabled. Can you confirm this is the case?

**Comment by Layendan** [comment]
my b for the late reply, yes this only happens with raw input enabled

**Comment by peppy** [comment]
This should already be fixed in the latest version.

**Comment by Gabixel** [comment]
For some reason, I can still reproduce this issue (no matter what option the raw input has)...
Also, the same problem still happens for example with the shortcut to change the language (<kbd>Windows</kbd> + <kbd>Space</kbd>). See #8064.

**Comment by Gabixel** [comment]
I have tested on various old versions and it seems that these problems have started happening from the release [`2020.613.0`](https://github.com/ppy/osu/releases/tag/2020.613.0) using `--sdl`.
The only visible difference appears to be the OS cursor that is hidden starting from that version, but I don't know how much it affects this problem.

**Comment by peppy** [comment]
I'm still unclear: does activating game bar *once* cause keys to never work again? Or are you expecting keys to pass through game bar in its new "transparent" mode or whatever they call it?

**Comment by Gabixel** [comment]
My only expectation is that *after* closing the game bar (by clicking on the transparent area or pressing ESC) or when switching keyboard layout (using its shortcut), all the input should work in lazer again (as anyone would expect). But as mentioned in https://github.com/ppy/osu-framework/issues/2198, https://github.com/ppy/osu-framework/issues/2525, #8064 and others, for some reason, something seems to be blocking various inputs (like `Space`, `ESC`, all shortcuts and textbox fields)

**Comment by peppy** [comment]
Thanks, so it's a permanent thing, that helps.

**Comment by Gabixel** [comment]
The last interesting thing I noticed is that when I change key bind after closing the game bar, or after changing keyboard language, the `Win` key is added along with the key pressed:

![game bar](https://user-images.githubusercontent.com/43073074/105685447-5d95db80-5ef6-11eb-9015-382372436199.gif)

**Comment by peppy** [comment]
I see, that helps heaps. Means the key is getting stuck in a depressed state, according to SDL2. I'm guessing it's also timing dependent, since I can't reproduce by progammatically sending the keystrokes.

**Comment by Susko3** [comment]
The Win+Space problem has been reported by me to SDL: https://github.com/libsdl-org/SDL/issues/4369

> The popup doesn't take window focus from the SDL window (the window will appear to be in focus), but it takes keyboard focus (pressing keyboard keys doesn't produce SDL_KEYUP/DOWN events).

The game bar also does this, so it's probably the same underlying problem.

**Comment by Layendan** [comment]
I know that this might not be of much help anymore, but it keeps all keys pressed in a pressed state. Whenever I play any game (eg. Valorant...) and I am holding another key when pressing Win + G, and maybe even Win + Space although I have not tested that, the game still considers it as I have that key held down (eg. Walking forward when pressing Win + G) makes you keep walking forward even when you let go of the key while the game bar is up. Generally, this fixes itself in the other games when I press that key again, but that might be because of the key overriding the previous action in those games I play.

I know that this is off-topic, but I hope it might help you in some way.

**Comment by Susko3** [comment]
This issue is fixed in SDL with commit https://github.com/libsdl-org/SDL/commit/3b85e3fdfce01c528a6ebf9ac537bdc106ba4963
