### ISSUE TITLE
Launching AppImage on Linux causes X11 to hang

### ISSUE THREAD

**Issue by shinotheshino** [ppy/osu#14085]
**Describe the bug:** 
When launching release 2021.731.0 on my Linux computer, my X Server hangs and osu! does not open. The only way to recover is to switch to another TTY. I am running Manjaro, with Linux 5.10.53.

This issue did not happen on prior builds.

**Screenshots or videos showing the encountered issue:** 
Due to the nature of the bug, I'm unable to get a screenshot. Here is the stdout/stderr from the AppImage:
```
cp: cannot create regular file '/home/shino/.cache/thumbnails/normal/b986ba7d6d7134ffab9d08b0a517813b.png': No such file or directory
touch: cannot touch '/home/shino/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  380
  Current serial number in output stream:  382
```

**osu!lazer version:** 
Release 2021.731.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6911300/database.log)
[network.log](https://github.com/ppy/osu/files/6911301/network.log)
[performance.log](https://github.com/ppy/osu/files/6911302/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6911303/runtime.log)

**Comment by bdach** [comment]
This is an upstream SDL failure. See: https://github.com/libsdl-org/SDL/issues/4561

**Comment by aisuneko** [comment]
Same issue here. Running Debian Bullseye with KDE 5.20, kernel 5.10.0.

**Comment by bdach** [comment]
yes. we know, thanks. please keep +1 comments to reactions instead.

this is already mitigated upstream and a fix will be following soon.

**Comment by gagahpangeran** [comment]
I believe this is already resolved with recent SDL bump in framework.

**Comment by frenzibyte** [comment]
Correct. [2021.808.0](https://osu.ppy.sh/home/changelog/lazer/2021.808.0).

**Comment by SrIzan10** [comment]
still doesn't work over here. Latest version, VirtualBox Ununtu VM.
