### ISSUE TITLE
Beatmap star rating range display and beatmap count display not working on "recently ended" etc. tabs

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14787]
Choosing either the "recently ended", "participated" or "owned" tab, the star rating display AND beatmap count display doesn't work (except it sometimes does as you can see in the video, but even then it only shows one beatmap, even though I know there were multiple beatmaps chosen).

Video:

https://user-images.githubusercontent.com/81645139/133836647-68196da8-dbba-4dc4-9a9b-fb3c24ffa02c.mp4

Logs (not sure if helpful in this case):
[database.log](https://github.com/ppy/osu/files/7187777/database.log)
[network.log](https://github.com/ppy/osu/files/7187778/network.log)
[performance.log](https://github.com/ppy/osu/files/7187779/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7187780/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7187781/updater.log)

**Comment by peppy** [comment]
This looks to also have been resolved with recent design updates.

**Comment by minasminas** [comment]
This also doesn't look resolved to me, I tested it again and it still shows nearly every lobby as 0.00 Stars with 0 beatmaps, even though I know that is not correct. Have you tested it and it worked on your end??

**Comment by peppy** [comment]
Yes I tested and it looked correct. Maybe you are looking at multiplayer instead of playlists and didn't specify that in the title? In which case that's probably broken, because multiplayer doesn't have proper history support yet.
