### ISSUE TITLE
Installation fails if current user has unicode symbols in login

### ISSUE THREAD

**Issue by XiaoWeiYT** [ppy/osu#18369]
### Type

Other

### Bug description

When I try to install OSU!Lazer he throws an error
The above is written like this: `An error occurred while running setup. Error Code: 17. Unable to extact selected file frome archive`
I have tried installing with an older version, but still to no avail

### Screenshots or videos

![image](https://user-images.githubusercontent.com/97890640/169837063-ca9d1ffb-a57a-4817-99cc-acc635e27182.png)

### Version

OSU!Lazer 2022.523.0

### Logs

No logs :(

**Comment by peppy** [comment]
What is your operating system?

**Comment by XiaoWeiYT** [comment]
> What is your operating system?

https://youtu.be/Zh5YQAAclBE

**Comment by bdach** [comment]
Looking at clowd.squirrel source based on the error message, the trace of this seems to be:

* Installer entry point calls [`util::extractUpdateExe()`](https://github.com/clowd/Clowd.Squirrel/blob/139ed410fe77e5ea39c722c7cd46f051cd108f7d/src/Setup/Setup.cpp#L46)
* which calls [`util::extractSingleFile()`](https://github.com/clowd/Clowd.Squirrel/blob/139ed410fe77e5ea39c722c7cd46f051cd108f7d/src/Setup/platform_util.cpp#L280)
* which seems to fail at [`mz_zip_reader_extract_to_file()`](https://github.com/clowd/Clowd.Squirrel/blob/139ed410fe77e5ea39c722c7cd46f051cd108f7d/src/Setup/platform_util.cpp#L254-L255)
* `miniz` seems to be a small embedded zip library with its own error codes, and error code 17 would unmap - if I'm looking correctly - to [`MZ_ZIP_FILE_OPEN_FAILED`](https://github.com/clowd/Clowd.Squirrel/blob/139ed410fe77e5ea39c722c7cd46f051cd108f7d/src/Setup/miniz.h#L1045)
* which is caught and printed [back at the entry point](https://github.com/clowd/Clowd.Squirrel/blob/139ed410fe77e5ea39c722c7cd46f051cd108f7d/src/Setup/Setup.cpp#L54)

If this trace is correct, then this would possibly indicate broken file permissions albeit it is tough to say for sure. Would probably need to run Process Monitor during the extraction process and see which underlying winapi call is failing.

(cc @caesay - any ideas?)

**Comment by caesay** [comment]
It could be file permissions, but I think it's [probably more likely to be this line].(https://github.com/clowd/Clowd.Squirrel/blob/139ed410fe77e5ea39c722c7cd46f051cd108f7d/src/Setup/platform_util.cpp#L253)

`fileLocation` will be a temp file in `%temp%`. We convert the wstring to a utf-8 string, and then miniz internally calls `fopen_s`. This will fail to open a file handle if there are any characters that are more than one byte long (eg. if the windows username has any unicode characters in it). 

Can @XiaoWeiYT confirm if there are any unicode characters in their username? or in the path to `%temp%`?

This issue has been fixed in the latest 3.x branch (`cs/xplat`) by [calling `_wfopen_s` instead](https://github.com/clowd/Clowd.Squirrel/blob/cs/xplat/src/Setup/platform_util.cpp#L261).

**Comment by XiaoWeiYT** [comment]
OH I just didn't know what I pressed and it seems to be fixed

**Comment by bdach** [comment]
If this is spuriously fixed then I guess we have nothing to investigate anymore...

Closing for now, if anyone else runs into this please bump and we'll reopen to investigate again.

**Comment by FrzMtrsprt** [comment]
Same problem here, I have unicode characters in my Windows username, and the installer fails with the same error code.

**Comment by bdach** [comment]
I'll reopen for the time being but for now I don't think we can do anything else than wait for the upstream fix to squirrel.

**Comment by caesay** [comment]
This is fixed in Squirrel v3, so is now waiting on osu upgrading. If you are not planning on upgrading soon I can backport the fix to v2 also?

**Comment by bdach** [comment]
Oh, I'd looked that the branch still exists and the latest release version has a 2.9.40 version, but didn't realise that 3.0.x packages are available for consumption (as unstable).

Probably fine to have this track upgrading then? Not sure there's much need to backport, this doesn't seem like something that affects very many users.

**Comment by caesay** [comment]
There was another bug with unicode characters that popped up with the installer so I have fixed this and released as 2.9.42.

**Comment by FrzMtrsprt** [comment]
I can confirm that the latest version (2022.1228.0) can install on my system with a unicode username. Sorry for not confirming this earlier, I had no idea when the installer was updated to 2.9.42.
