### ISSUE TITLE
Rotating sliders in the editor freezes the game

### ISSUE THREAD

**Issue by maximium91** [ppy/osu#20208]
### Type

Performance

### Bug description

Trying to rotate sliders in the editor causes the game to lock up completely for a few seconds.

### Screenshots or videos

Here I tried rotating a slider and it froze my game for about 14 seconds.

https://user-images.githubusercontent.com/107336266/189368607-8544eedb-f4a8-4bee-aea7-6265eb4db9dd.mp4

### Version

2022.902.1-lazer

### Logs

[performance-update.log](https://github.com/ppy/osu/files/9536092/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9536093/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9536094/updater.log)
[database.log](https://github.com/ppy/osu/files/9536095/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9536096/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9536097/network.log)
[performance.log](https://github.com/ppy/osu/files/9536098/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9536099/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9536100/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9536101/performance-input.log)

**Comment by peppy** [comment]
I can't seem to reproduce this. Can you try on a different beatmap? If it only happens on specific beatmaps, can you please link the map?

**Comment by maximium91** [comment]
Just now tried 6 different maps, happens consistently on all maps and all sliders.
Happens with slider control points too...

https://user-images.githubusercontent.com/107336266/189373792-e17ef901-f4d6-4800-9ca2-34d9ec732e2e.mp4

Also looks really weird when recorded at 30fps?

**Comment by maximium91** [comment]
This doesn't look good.
Memory usage keeps going up steadily as im typing this

![image](https://user-images.githubusercontent.com/107336266/189379921-44c40846-c9c0-4cdc-9ef0-257d67404487.png)

**Comment by HiddenNode** [comment]
I was able to reproduce this but only after rotating a slider for some time.

https://user-images.githubusercontent.com/101936124/189480260-9126110a-7fe9-4696-8c9a-a58d7c6877e8.mp4


running this through the debugger it seems like the lag is caused by the GC.

**Comment by peppy** [comment]
This may already be fixed in latest `master`, there was a dangling bindable reference which was recently fixed. Can you try on a dev build?

**Comment by HiddenNode** [comment]
I've just tried on the latest master and the issue persists.

**Comment by peppy** [comment]
I've applied one fix for this issue, but it looks like this only delays the inevitable performance death.

The remaining issue seems to be https://github.com/ppy/osu/issues/11261 (with a proposed fix at https://github.com/ppy/osu/pull/11262). I'll bump that up in priority.
