### ISSUE TITLE
Scores imported from stable use ScoreV1 value despite standardised scoring enabled

### ISSUE THREAD

**Issue by bdach** [ppy/osu#23756]
### Type

Game behaviour

### Bug description

1. Import a stable score
2. Go to leaderboard of the map the stable score was set on
3. The beatmap leaderboard will use the raw ScoreV1 value from the replay, rather than a recomputed ScoreV2 analogue, causing the leaderboard to contain fundamentally incomparable stable scores (uncapped) and lazer-only scores (capped to 1M).

Regressed due to https://github.com/ppy/osu/pull/23638/files#diff-f83261c3fa399856c647f34ec303775b78826663ff84e05910ed4cfaf63ef9a9L77-R78.

Fixing would require a method of converting ScoreV1 score values to ScoreV2 standardised values, *somehow*.

### Screenshots or videos

| | standardised scoring | classic scoring |
| :-: | :-: | :-: |
| 2023.513.0 | ![osu_2023-06-05_20-43-13](https://github.com/ppy/osu/assets/20418176/e53b63cd-4c68-4a35-bc6d-212dc8eaf4bd) | ![osu_2023-06-05_20-43-19](https://github.com/ppy/osu/assets/20418176/3a42d3fe-0388-405d-958e-180a0dac696f) |
| 2023.605.0 | ![osu_2023-06-05_20-44-43](https://github.com/ppy/osu/assets/20418176/5006d81e-803a-487c-bb7b-39d829015f2f) | ![osu_2023-06-05_20-44-52](https://github.com/ppy/osu/assets/20418176/612308e5-b189-4078-a13f-390f1da0a52f) |

### Version

2023.605.0 / current master

### Logs

\-

**Comment by peppy** [comment]
Should this be resolved via #23817?

**Comment by smoogipoo** [comment]
Yes I'm still working on converting scores. This PR isn't resolved, the mentioned PR was a temporary fix to prevent scores in the billions.
