### ISSUE TITLE
Error everytime while using the Synesthesia Mod

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ppy/osu#23983]
### Type

Game behaviour

### Bug description

1. Have the Synesthesia mod on
2. Play a map
3. Either leave the map mid way through the song or retry the map
4. Get the error

Note this bug only works with maps with leaderboards

### Screenshots or videos

![Screenshot 2023-06-21 025359](https://github.com/ppy/osu/assets/107338855/af345c4b-d94e-4b7b-82be-5335701225e8)

### Version

Lazer 2023.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/11815187/database.log)
[input.log](https://github.com/ppy/osu/files/11815188/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11815189/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11815190/network.log)
[performance.log](https://github.com/ppy/osu/files/11815191/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11815192/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11815193/updater.log)

**Comment by ParaliyzedEvo** [comment]
Doesn't have to fixed asap but just a bug I just wanted to tell you guys

**Comment by peppy** [comment]
This is already fixed, we're deploying it at the moment so please try again soon.

**Comment by 0xallie** [comment]
How long is the deployment expected to take? I'm still seeing this issue.

**Comment by peppy** [comment]
It should be done now. I fucked up the deploy process because I don't know how it works.
