### ISSUE TITLE
Icon in volume mixer is too big

### ISSUE THREAD

**Issue by theLMGN** [ppy/osu#2424]
It's a small bug, but it's one 
![image](https://user-images.githubusercontent.com/12257112/39008747-76f14a14-4401-11e8-8e67-e8c4c0dac2b8.png)

Icon resolution is 64px, should be 32px

**Comment by peppy** [comment]
What operating system are you seeing this on? Please provide full details including language and version.

**Comment by theLMGN** [comment]
@peppy Windows 10 (1607, 14393.2189) with the English - UK Locale.

**Comment by jorolf** [comment]
![screenshot](https://user-images.githubusercontent.com/12570757/39088474-0c1a362a-45b3-11e8-8022-a3f0681a4236.png)

The icon is the correct size for me.
I'm using Windows 10 (Version 10.0.16299.371 aka. Fall Creators Update) with the German locale

**Comment by FreezyLemon** [comment]
Seems to be related to [high DPI settings](https://stackoverflow.com/questions/17949693/windows-volume-mixer-icon-size-is-too-large).

**Comment by theLMGN** [comment]
Hmm, odd I don't use DPI scaling on my machine.

**Comment by peppy** [comment]
Guessing this is still an issue even with the .net core releases?

**Comment by KisaragiEffective** [comment]
2019.730.0 still has

**Comment by Maoman1** [comment]
The icon also seems to have been scaled up massively, though I'm not using any DPI scaling. That is [this setting](https://i.imgur.com/U4iDKqg.png), correct?

ver 2020.327.0
Windows 7 pro

![](https://i.imgur.com/GRFl1Ts.png)

**Comment by peppy** [comment]
A temporary solution is to update to a non-legacy version of windows.

**Comment by Maoman1** [comment]
I have to use windows 7 for work, but thanks for clarifying where your priorities lie.

**Comment by peppy** [comment]
As an aside, this will probably be fixed via switch to SDL.

**Comment by Joehuu** [comment]
@theLMGN @Chisk @KisaragiEffective @Maoman1 can you still reproduce this weird bug on the latest release? We recently switched to SDL as the default, and maybe that fixes it.

**Comment by KisaragiEffective** [comment]
I'll check it later.

**Comment by ThatsNiceGuy** [comment]
![image](https://user-images.githubusercontent.com/10524728/103826870-f1c9fc80-5034-11eb-9cb8-4d456727fad6.png)
osu!lazer 2020.1229.0 but this is HiDPI, 4K 144hz 27" with 175% scaling


![image](https://user-images.githubusercontent.com/10524728/103826963-1f16aa80-5035-11eb-985a-deb120753cb9.png)
this is no hidpi, same 4k as before but i set to 100% scaling and restarted

looks fixed to me

**Comment by Joehuu** [comment]
If you look at https://github.com/ppy/osu/issues/2424#issuecomment-383900573 and the other comments, hidpi is not the cause.

**Comment by ThatsNiceGuy** [comment]
That is why I provided screenshots for hidpi off too, just in case.

**Comment by peppy** [comment]
That's fine, but this also was not affecting everyone (I could not reproduce, for instance) so I'd be grateful to hear from one of the original reported that was experiencing the issue in the first place to confirm it is fixed (and that starting the game with `--tk` makes it broken again).

**Comment by peppy** [comment]
Going to close this as "probably fixed by SDL".
