### ISSUE TITLE
Rate-changing mod setting UX

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24674]
### Type

Game behaviour

### Bug description

Initially discussed [IRL then on osu!dev](https://discord.com/channels/188630481301012481/188630652340404224/1145959465808564224).

General questions being raised here are:

- Current minimum of DT is 1.01x, current maximum of HT is 0.99x. This is basically the same as nomod. Should this continue to exist?
- We're currently rounding multiplier down to the nearest multiple of 0.1, for both HT and DT, to curtail cheesing even if slightly. How to best communicate this to the user?

### Version

n/a

### Logs

n/a

**Comment by S1n1st3rn3ss** [comment]
I think I've asked this before but since it is relevant I'll ask again, as I wanna know what's the vision for this is

1) Is there a real reason for using steps of 0.1x instead of 0.05x or is it just something that feels more correct? Because larger steps create a small issue with using said rates on maps with high base bpm - a step of 0.1x might feel too large (e.g. 1.1x on [Shinbatsu](https://osu.ppy.sh/beatmapsets/482382) increases bpm from 240 to 264)

2) Is there a reason to not simply disallow precision higher than 0.1x (or hide it behind a mod setting)? Explaining limited precision or a toggle would be much easier than explaining the round down for submitted scores and, at least to me, it makes more sense

**Comment by monochrome22** [comment]
As I suggested in [Discord](https://discord.com/channels/188630481301012481/188630652340404224/1146007901526294609), I think a decent solution would be to display rate changes on the mod icon, as suggested in https://github.com/ppy/osu/discussions/15262#discussioncomment-1526777, so if someone uses 1.01x, players would immediately be able to tell that the double time addition on the score doesn't really matter. 

I think the biggest issue with removing 1.01x would be [manual BPM input](https://github.com/ppy/osu/discussions/22616). Obviously, not just 1.01x would be removed, but also anything under 1.05x (probably). If these more precise values are removed, it would mean many beatmaps would become inaccessible to be played with a certain BPM, so the player would not see them if they set a certain BPM and only play maps with that BPM. 

Also, 1.01x can have practical uses. There have been times when I want to FC a map with 1.10x speed, but going straight into 1.10x is too fast, so I start slower by using 1.01x, FCing, then moving to 1.02x, FCing, etc. Of course, from nomod to 1.01x, there is no noticeable difference, _and that's the point_. You can move progressively and become able to FC at higher speeds without noticing any uncomfortable difficulty increase. So going straight into 1.10x would be too difficult, but moving to it progressively would be comfortable. 

Another point to keep in mind is that this issue is not specific to double time and half time. There are multiple mods that can be added without it really doing anything. For example, Accuracy Challenge mod with 60% requirement, Wind up and Wind down, Wiggle at 0.1 strength, and most importantly: Difficulty Adjust. Even if you limit Double Time to 1.05x lowest and other mods to a point where they are not a free icon, then players would still be able to do things like change HP by 0.1 on Difficulty Adjust and have a "pointless icon" show. Trying to force a rule where mods can only work in a way where they have a noticeable impact on gameplay seems like a lost cause; it wouldn't work on something like Accuracy Challenge, where whether the setting is pointless or not depends on the map and player.
I can agree that it would be a bit silly to have scores that have 4 mods on and none of the mods really do anything. Maybe give special treatment to mods that didn't have a significant impact on gameplay. For example, if the score is 95% accuracy and the user has 60% requirement Accuracy Challenge, 1.01x Double Time and +0.1HP Difficulty Adjust, then instead of displaying the 3 mod icons normally, they all get put under one icon like "Misc." or "Other", and the mods will be listed when hovering the icon.

As for communicating the multiplier, just having the Mod Multiplier visible in mod select while adjusting the speed setting would probably be enough to have players quickly understand that the mod multiplier only changes at 0.1x steps. Currently, the mod multiplier is not visible while adjusting speed settings, meaning it's not obvious to players that it only changes at certain settings. Maybe also play a sound effect if the mod multiplier changed while adjusting settings.

**Comment by bdach** [comment]
Many ideas here but I'm not immediately sure how to progress this issue out of discussion phase. I guess the conversation here would be twofold: first, what the players want out of this feature, and second, how to display it to them. The first is probably a hard blocker for the second.

@Bubbleman532 this is possibly a bit of your wheelhouse but maybe have a look through and see if you can think of anything to offer here?

**Comment by Bubbleman532** [comment]
Our discussion boiled down to a couple points. The first is that 0.01 increments are used when people try to match the new bpm to a round number, for example playing Everything Will Freeze at 270bpm is 1.12x, so could stick around. The second however is that 0.01 is too small an increment to rank because 1.01 is indeed too small of a change to notice.

We're looking at something else to do with rate changing and how score multipliers should work with mods in general (spawned off the rate changing discussion), but for now the consensus is that the rate change slider should move in 0.05 increments but there should be an "unlock" button that allows changes in 0.01 increments and unranks the score.

**Comment by peppy** [comment]
To confirm, you're proposing disallowing scores set at 1.12x speed adjust from submission to leaderboards?

This conflicts with our current direction, which is that there's no such thing as "unranked" play – every setting is expected to end up on the leaderboard in some way or another.

Which is why the current way things are handled in the live build is to round down to the previous multiplier (ie. 1.10x, 1.11x, 1.12x, 1.13x 1.14x get treated as a 1.10x score). Is this behaviour in itself seen as a bad direction for multiplier implementation?

**Comment by Bubbleman532** [comment]
'there's no such thing as "unranked" play'

Something else to discuss I guess - a few share my opinion that not everything should be ranked (by which i mean directly give pp), but I haven't put it out to enough of an audience yet to get the general viewpoint

**Comment by bdach** [comment]
> a few share my opinion that not everything should be ranked (by which i mean directly give pp)

I have no horse in this particular race but I'll just mention offhand that I'm not sure the two need to be linked together, either, for whatever that's worth. Technically there's nothing stopping us from doing `return 0;` in pp calculation code for whatever combination of criteria. Whether that's *palatable* by everyone is another conversation entirely I guess...

**Comment by Bubbleman532** [comment]
It's a terminology issue then, where most of the community hear "ranked" with the connotation of "pp", and "unranked" being things like Loved or Qualified etc - I'm in agreement that the two don't need to be linked, it would be a lot of fun to have the Fun mods be leaderboard-enabled whilst not affecting the "ranked" (pp) performance-focused portion of the game

**Comment by monochrome22** [comment]
Whether or not unranked should exist should not be determined by any opinions, but rather by whether or not it's possible to practically balance mods and their settings in a way that is reasonable. If you're going to ask stable users if mods should be unranked, naturally they would say "A mod is difficult to balance? Just unrank it", because that's how they are used to dealing with difficult-to-balance mods. Instead of having a discussion about "should we unrank mods?", you should have a discussion about "how can we make this mod work in a way that is reasonable?". Unranking should be a last resort.
Personally I think rate adjust is heading in a good direction, there seem to be many solutions to make it work well. Locking rate adjust to certain increments with the option to unlock is a good idea. It helps with players understanding that certain increments are more important, combine that with displaying mod multiplier during mod adjust and there shouldn't be any issue with confusion. Difficulty Adjust would be a more complicated case though, if there are increments, they would have to depend on the stats of the select map.

**Comment by peppy** [comment]
So I guess the take away here is that @Bubbleman532's surveyed population thinks the score multiplier should round to the nearest 5% rate change.

As for the UX, I guess I'll take that on myself since there doesn't seem to be any strong opinions or good suggestions.

**Comment by peppy** [comment]
I'm going to move this to implementation phase since I don't think we'e going to get much feedback here without implementing some improvements to the UX and getting feedback post-implementation.

**Comment by DigitalHypno** [comment]
Last week, Wixonater and I interviewed a random sample of 5 osu!standard players to discuss this topic and gather feedback on lazer's UI as a whole. The feedback that was relevant to this PR is summarized below. All of the feedback can be found [here](https://honmi.notion.site/osu-lazer-Mod-UI-Usability-Interviews-61438674376c4545bcc487b324c6fb22), but most is irrelevant to this PR.

---

***Current minimum of DT is 1.01x, current maximum of HT is 0.99x. This is basically the same as nomod. Should this continue to exist?***

- **Consensus among interviewees:** Most agreed that the lower DT rates were very similar to nomod, but saw no harm in leaving them as options in the game.

---

***We're currently rounding multiplier down to the nearest multiple of 0.1, for both HT and DT, to curtail cheesing even if slightly. How to best communicate this to the user?***

- **Consensus among interviewees:** Firstly, the difficulty multiplier should still be on the screen when the mod customization menu is open. Other than that, some suggestions from the players include: 
    - displaying the current multiplier that DT/HT is providing in the mod customization menu itself, right next to the mod's icon and name.
    - adding an "advanced tooltip" that would appear when hovering the "Speed increase" text with the Shift key (or something similar) that explains how the multiplier works.

I personally believe that the line visuals mentioned by monochrome22 could also work, but the first sub-bullet above should help a lot (along with keeping the current multiplier visible in the mod customization menu).

---

I should also add that some players struggled to make precise adjustments to the speed increase slider, particularly if they were using a tablet pen to move the slider. A manual input box for typing a rate change value was suggested by some, is something similar to #22616 possible?

Also, most players assumed that the arrow keys would nudge the slider by 0.01x instead of 0.10x, which I also think would be much more intuitive and help make precise adjustments easier.

**Comment by bdach** [comment]
> As for the UX, I guess I'll take that on myself since there doesn't seem to be any strong opinions or good suggestions.

I'll assign to you for now then.

**Comment by Givikap120** [comment]
the only thing that's bad with this - confusing DT icon in score display
it's already gives the same amount of Score as NM does
and pp is about the same (1.01x difference is super minor)

giving different icons (colors?) for DT 1.01-1.09, 1.1-1.19... would fix the problem
but how to design them properly - idk

**Comment by peppy** [comment]
@arflyte I think I may have touched on this in the past, but we need some mod icons to show a value on them. For "double time" and "half time", showing a multiplier would be optimal in the icon itself (or somewhere above/below it?). This wouldn't be the case for every mod, but for mods with an important setting we'd want to let users quickly assess what that setting's value is.

For double time, the range would be something like `1.01x` ~ `2.0x`.
For half time, the range would b something like `0.5x` ~ `0.99x`.

**Comment by arflyte** [comment]
Oh yeah, forgotten about this. Working on mod components now, so I'll address this issue at the same time.

**Comment by peppy** [comment]
> Oh yeah, forgotten about this. Working on mod components now, so I'll address this issue at the same time.

Keep in mind that this is part of our requirements for lazer leaderboards, so consider it high priority.

**Comment by Tanza3D** [comment]
![image](https://github.com/ppy/osu/assets/33783503/85ea8d63-67c9-49a5-a5a8-66cb7f10b72f)
these are the ideas i've got for these, also two different font choices (venera and torus)
i think torus is the better choice here, and (for now) the gray background i feel fits the best, especially in the score screen

this is at low resolution as it lines up for the resolution the mod icons use in leaderboards:
![image](https://github.com/ppy/osu/assets/33783503/fd36e7d8-91e6-47cf-a14d-966a261e976f)

the gray background may look out of place going forward with new UIs though, so using a more red-ish one (and green for HT) would be more in-line with new designs, but looks more out of place with older designs in my opinion:
![image](https://github.com/ppy/osu/assets/33783503/1479c310-9039-4bef-b69d-266f6d70e95d)


this would also show up on results screens as well, but i feel it's reasonable to leave it out in the mods overlay and song select toolbar, the user probably knows what they've got selected (the main issue is that the mods overlap eachother, and one at a wider length would look wonky)

![image](https://github.com/ppy/osu/assets/33783503/7728ce84-48b9-4a0a-875e-9b79ec0d956c)

[figma](https://www.figma.com/file/ezQwPY41kv5PSkTDrEjWhl/Untitled?type=design&node-id=1-567&mode=design&t=TctNrEIcPx7KtqeS-4)

**Comment by bdach** [comment]
I dunno, I'd say "dark colour" is best. The contrast of the gray with the red is pretty weak IMO, looks rather difficult to read.

Also, in a few places we use these:

![image](https://github.com/ppy/osu/assets/20418176/06b8eb60-69bd-45f7-b386-302d12f8a0dc)

Not sure whether we should be bothering to attempt to display DT/HT rate on these at all?

**Comment by Tanza3D** [comment]
i'd be good with dark colour too yeah, either works, just felt the gray was a bit more in-line with the current song select to me atleast

also yeah, as i said in my last paragraph i feel it's best we avoid it on the toolbar and mod overlay, i feel users should know what they selected themselves (there's also already a 0.00x number there, adding another would be confusing)

**Comment by peppy** [comment]
I think we should go with the non-gray colour, as I hope to remove the ugly gray from the results screen sooner rather than later.

Design looks good to me. Torus feels correct.

**Comment by peppy** [comment]
@Tanza3D could you please export this piece without the cut off edge? I can't make it work:

![Uploading Untitled 2.png…]()

**Comment by substanc3-dev** [comment]
@peppy this should be a proper export:

[side piece](https://github.com/ppy/osu/assets/6898693/c17ffd67-3b75-4447-8fcd-46d4c045a09d)

**Comment by Tanza3D** [comment]
haha i just finished doing that.. here's one in the same resolution as peppy sent though (height-wise)
[side piece](https://github.com/ppy/osu/assets/33783503/b11b40dd-dd9b-4061-a945-9a0a409db722)

**Comment by peppy** [comment]
Thanks much.

**Comment by peppy** [comment]
@Tanza3D that export has incorrect transparent pixels. is that straight from figma?

![osu Game Tests 2023-09-27 at 09 34 31](https://github.com/ppy/osu/assets/191335/a3839d51-ab88-4355-a4e2-c74b130d18b5)

**Comment by Tanza3D** [comment]
yeah it's straight from figma, but i did export it in a bit of a strange way - maybe try this one?
[fixed](https://github.com/ppy/osu/assets/33783503/86ce3dbe-9081-4652-b14b-484068d5e12a)

**Comment by peppy** [comment]
> yeah it's straight from figma, but i did export it in a bit of a strange way - maybe try this one? [fixed](https://github.com/ppy/osu/assets/33783503/86ce3dbe-9081-4652-b14b-484068d5e12a)

Nope, still broken

![osu Game Tests 2023-09-28 at 07 05 10](https://github.com/ppy/osu/assets/191335/a8ee7cba-6051-4b0a-9a60-d19af78eae1f)

I guess figma is another app on the blacklist of doing things right.

**Comment by substanc3-dev** [comment]
This should hopefully be fixed @peppy
[Subtract](https://github.com/ppy/osu/assets/6898693/23ae927d-a648-4236-8f84-3a0f7b6d14c1)
