### ISSUE TITLE
Increasing mouse sensitivity makes the cursor go flying

### ISSUE THREAD

**Issue by ry00001** [ppy/osu#2486]
Evidence: https://tetris-is.theworstme.me/424ded.mp4 
Had to upload to a service because GitHub doesn't support .mp4 files lol

Windows 8.1 Pro (version 6.3 build 9600)
osu!lazer 2018.502.0
Tablet attached: Huion H420 (I was using a mouse there though, not sure if this matters)
8GB RAM
GTX 1050Ti
AMD A6-6400K @ 3.9 GHz (dual-core)

**Comment by peppy** [comment]
Does this happen just by toggling on raw input (ie. at ssensitivity 1.0x)?

**Comment by jorolf** [comment]
I don't know if this is the same problem but I've been experiencing something similar: https://streamable.com/vkidv

**Comment by ry00001** [comment]
@peppy no, it doesn't, i have to explicitly turn the sensitivity up for it to happen

**Comment by ry00001** [comment]
and @jorolf it looks like a separate issue but may be related

**Comment by jorolf** [comment]
Can you try to change the sensitivity to the same values I did?

**Comment by ry00001** [comment]
@jorolf I get that issue too if i turn sens *down* instead of up

**Comment by SarahIsWeird** [comment]
This is exactly my problem I am having. Toggling on raw input and then increasing the mouse sensitivity even the smallest bit makes it spaz out. If you change it just a little it will move out but jump back to where it was before and if you change it a lot it just goes flying off to the edges without coming back. Note that I have a tablet connected, but when I disconnect the tablet the cursor just moves down at a moderate speed and dragging it up is hindering it, but not stopping it.

**Comment by morguldir** [comment]
Should be fixed in the latest version, could you test?

**Comment by SarahIsWeird** [comment]
Sorry for not checking earlier. Yes, everything's working fine now!

**Comment by Diegomastro** [comment]
I'm still having this issue, the mouse goes to the corners and now I cant turn off raw input
