### ISSUE TITLE
Some maps keep failing to import

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#2742]
Trying to import beatmaps from stable works for MOST maps now, although a total five of my maps failed to import, all throwing the same error; an `SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.` The specific error message seems to differ from case to case.
Here is one example:
```06.06.2018 15:44:05: Failed executing DbCommand (0ms) [Parameters=[@p10='?', @p11='?', @p12='?', @p13='?', @p14='?'], CommandType='Text', CommandTimeout='10']
06.06.2018 15:44:05: INSERT INTO "BeatmapSetInfo" ("DeletePending", "Hash", "MetadataID", "OnlineBeatmapSetID", "Protected")
06.06.2018 15:44:05: VALUES (@p10, @p11, @p12, @p13, @p14);
06.06.2018 15:44:05: SELECT "ID"
06.06.2018 15:44:05: FROM "BeatmapSetInfo"
06.06.2018 15:44:05: WHERE changes() = 1 AND "ID" = last_insert_rowid();
06.06.2018 15:44:05: An exception occurred in the database while saving changes for context type 'osu.Game.Database.OsuDbContext'.
06.06.2018 15:44:05: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.
06.06.2018 15:44:05: bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
06.06.2018 15:44:05: bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
06.06.2018 15:44:05: --- Ende der internen Ausnahmestapelüberwachung ---
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
06.06.2018 15:44:05: Import of 630109 Guilty Kiss - Shadow gate to love failed and has been rolled back.
06.06.2018 15:44:05: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.
06.06.2018 15:44:05: bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
06.06.2018 15:44:05: bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
06.06.2018 15:44:05: --- Ende der internen Ausnahmestapelüberwachung ---
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
06.06.2018 15:44:05: bei Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
06.06.2018 15:44:05: bei osu.Game.Database.DatabaseWriteUsage.Dispose(Boolean disposing)
06.06.2018 15:44:05: bei osu.Game.Database.DatabaseWriteUsage.Dispose()
06.06.2018 15:44:05: bei osu.Game.Database.ArchiveModelManager`2.Import(ArchiveReader archive)
```
I don't wanna post the entire error codes in here, so here's the log file: 
[database.log](https://github.com/ppy/osu/files/2077120/database.log)

Also here is one of the maps I've tried to import in zip format.
[630109 Guilty Kiss - Shadow gate to love.zip](https://github.com/ppy/osu/files/2077124/630109.Guilty.Kiss.-.Shadow.gate.to.love.zip)

**Comment by Morilli** [comment]
Update: Redownloading beatmapset 387784 made it possible to get imported, yet the one I specifically mentioned above (630109) doesn't get imported even after a redownload. I really can not tell what's wrong about the maps, so here are two .osz files that both fail to import.


[Exports.zip](https://github.com/ppy/osu/files/2090943/Exports.zip)

**Comment by cl8n** [comment]
the "Easy" difficulty of [Shadow gate to love](https://osu.ppy.sh/beatmapsets/630109) has its BeatmapID written incorrectly in the .osu file (it has the id of the "Kisses" difficulty instead). I'm not sure how that happened, but this error is supposed to occur in this case. @peppy I think you're the only one that can fix this, since the map is already ranked

the other set you linked had identical copies of each diff with a different creator (presumably because the creator changed their name along the way). delete+redownload should fix that

**Comment by peppy** [comment]
Even in such cases, importing should be fixed. In fact, #2761 may possible already solve this remaining one.

**Comment by Morilli** [comment]
Alright, so removing the conflicting .osu files from the beatmap folder before importing solves this issue, although obviously these .osu files do not get imported then. Also it is indeed very weird that there seems to be an error in the .osu file of [Shadow gate to love](https://osu.ppy.sh/beatmapsets/630109)'s "Easy" difficulty, and also [MONSTER](https://osu.ppy.sh/beatmapsets/661483)'s "Insane" difficulty (it's the same as the "EXPERT" difficulty), causing these two to throw an error as well.

**Comment by peppy** [comment]
Please check with latest master or the next public release (`2018.612.0`) and mark this as closed if it is fixed.

**Comment by Morilli** [comment]
Under the current release (2018.612.0) osu!lazer now throws a ton of errors when importing, looking like the following:
```
12.06.2018 14:52:53: Attempting online lookup for IDs...
12.06.2018 14:52:53: Failed (System.Net.WebException: Unauthorized
...
```
The previously failing maps still fail to import, all others work fine.

**Comment by peppy** [comment]
You will need to be logged in. That said, this probably should not block imports; will look into that.

Could you please try again after logging in, though?

**Comment by Morilli** [comment]
Logging in does actually solve that problem, didn't think of that. There is a problem I've experienced when trying to import while being logged out though, which is that the first beatmap that fails to do the online request gets beatmapset -1 assigned, at least that's what I remember from old log files, which means that this beatmap will get imported incorrectly. I don't know if the pull request would fix that. And as stated previously, the beatmaps failing earlier still fail to import.
[network.log](https://github.com/ppy/osu/files/2107287/network.log)
[database.log](https://github.com/ppy/osu/files/2107288/database.log)

**Comment by peppy** [comment]
Could you try to reproduce the logged out issue? We already fixed this to my knowledge.

**Comment by Morilli** [comment]
The issue still persists. Some maps get logged as succesfully imported even though they don't, while also mentioning an imported beatmap with beatmapset -1; here are two lines of such an import:
```
16.06.2018 10:48:05: Import of Mike Perry - The Ocean ft. Shy Martin successfully completed!
16.06.2018 10:48:05: Attempting online lookup for IDs...
```
This beatmap was not submitted and did also not get imported (while being logged out) even though osu!lazer logs it as imported. Further imports will make it continue to log that while not yielding any different results.
[network.log](https://github.com/ppy/osu/files/2108046/network.log)
[database.log](https://github.com/ppy/osu/files/2108047/database.log)

**Comment by Morilli** [comment]
So I am assuming imports for multiple beatmaps with the same BeatmapID is not intended? As such beatmaps still are not able to get imported.

**Comment by peppy** [comment]
examples?

**Comment by Morilli** [comment]
As commented earlier, Shadow gate to love's "Easy" difficulty, and also MONSTER's "Insane" difficulty are good examples.

**Comment by Morilli** [comment]
Reopening in #2970.
