### ISSUE TITLE
Unable to launch 2024.412.0 appimage

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#27836]
### Type

Other

### Bug description

Previous Appimage works fine, newest gives this error: 
/tmp/.mount_osu.ApOEuYqv/AppRun: line 13: exec: %U: not found

I've attempted redownloading the Appimage twice and am still getting this error.

### Version

2024.412.0

### Logs

.

**Comment by Yutsuten** [comment]
Same issue here, using Arch Linux. Reverting to the previous release fixed for me.

I had 3 errors:

```
cp: 通常ファイル '/home/mateus/.cache/thumbnails/normal/14d0f7f2b5a355efcc85a68f77a7060c.png' を作成できません: そのようなファイルやディレクトリはありません
touch: '/home/mateus/.local/share/icons/hicolor/.xdg-icon-resource-dummy' に touch できません: そのようなファイルやディレクトリはありません
/tmp/.mount_osu.ApI6kxUk/AppRun: 13 行: exec: %U: 見つかりません
```

I `mkdir`ed the directories missing, but the last error persists.

**Comment by refrainsclub** [comment]
Looks like the latest release of osu!lazer does not come with an AppImage.
Even the website download does not work.

**Comment by smoogipoo** [comment]
Should be fixed with the newest AppImage. https://github.com/ppy/osu-deploy/commit/28da7879486a1668cf8ac91e3eaa08d5cefe82cf

**Comment by Yutsuten** [comment]
I undid the `mkdir`s and the bellow errors still appear. In the previous release there errors didn't appear. The game opens with no problem, so I think it is safe to ignore.

```
cp: 通常ファイル '/home/mateus/.cache/thumbnails/normal/14d0f7f2b5a355efcc85a68f77a7060c.png' を作成できません: そのようなファイルやディレクトリはありません
touch: '/home/mateus/.local/share/icons/hicolor/.xdg-icon-resource-dummy' に touch できません: そのようなファイルやディレクトリはありません
```

Just reporting, no big deal. Thank you for the fast fix!
