### ISSUE TITLE
Osu!Lazer. New version but "Please ensure that you are using the latest version of the official game releases."

### ISSUE THREAD

**Issue by catarium** [ppy/osu#29013]
### Type

Game behaviour

### Bug description

I'm running unmodified version on Windows 11.
I've been getting this for months (almost since I started playing).
I've already tried:
- deleting files suggested on other posts about this issue like "AuthNative.dll", "client.realm", "client.realm.lock"
- deleting osu!lazer completely
- log out and log in
- running from different windows user

Also:
- I've tried to build from source and I didn't have the issue on developer test server.
- The issue appears and disappears for random periods of time.
- I didn't have the issue on stable.

And the problem in logs is the same as on other issues: "missing token header".

### Screenshots or videos

![image](https://github.com/user-attachments/assets/03e141bc-b692-4805-9d43-b2bd6d19a132)

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16338874/compressed-logs.zip)

**Comment by catarium** [comment]
Also, I had the same problem with UAC and running from admin as [here](https://github.com/ppy/osu/issues/29017) and [here](https://github.com/ppy/osu/discussions/28531). But fixing it by configuring UAC didn't solve the problem.

**Comment by The-Grace-God** [comment]
So I'm unsure if you have fixed this yet or not but a temporary fix is logging out then logging back in
what I'm assuming is happening is that during updating if the app is being ran with admin rights it doesn't know what to do with the token and it messes it up creating the score issue

**Comment by smoogipoo** [comment]
This (and all similar issues like it) should now be fixed.

**Comment by JamesGamesALot** [comment]
I am still having this issue.
![image](https://github.com/user-attachments/assets/2708f325-f2cd-4000-82e7-915551e4039f)
![image](https://github.com/user-attachments/assets/b87fcf51-44d2-4d88-b4b0-9b506ae1040d)

**Comment by smoogipoo** [comment]
Please provide logs (options -> export logs).

**Comment by catarium** [comment]
> I am still having this issue. ![image](https://private-user-images.githubusercontent.com/95728753/354485291-2708f325-f2cd-4000-82e7-915551e4039f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTY1MDAsIm5iZiI6MTcyMjYxNjIwMCwicGF0aCI6Ii85NTcyODc1My8zNTQ0ODUyOTEtMjcwOGYzMjUtZjJjZC00MDAwLTgyZTctOTE1NTUxZTQwMzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE2MzAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MGQ2N2VlZjFlZDUxNzY3NzYwOWRjYWJjNGFmMjMzYWNhM2M2MzA1MTIyMjIyODc1ZGU4YWU4Y2U0OGZmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GvBsAvKaz0R23fHApTqMAfLXAiB15KvHtZHK8sHsWfg) ![image](https://private-user-images.githubusercontent.com/95728753/354485534-b87fcf51-44d2-4d88-b4b0-9b506ae1040d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTY1MDAsIm5iZiI6MTcyMjYxNjIwMCwicGF0aCI6Ii85NTcyODc1My8zNTQ0ODU1MzQtYjg3ZmNmNTEtNDRkMi00ZDg4LWI0YjAtOWI1MDZhZTEwNDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE2MzAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODE3MDA5MTRlNmI4N2Q2NDBkYTg1YjljNjVlNTc1YWM5YzVmZWEwNjQyYmVhNTAwNmQ3NDhmYWQ0ZDcwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0KN_eRy9AmHaXHz2t8HhR6Q_ei3A2eHfky2FOUjXu18)

In my case issue still appears, but (mostly) can be fixed by restarting the game
