### ISSUE TITLE
Random "Edit externally" fails: "Export failed"

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29029]
### Type

Game behaviour

### Bug description

Hi. I was editing my map and was using also "Edit externally" option a lot. All of sudden, when I imported one of those, its folder (in Temp directory) didn't remove after that, and since then, it doesn't work anymore **for this map ONLY**:
![image](https://github.com/user-attachments/assets/4bd0d38c-bae2-4897-b44b-078782e612c2)

And the folder is also unremovable:
![image](https://github.com/user-attachments/assets/95086d33-89de-43a6-aa21-4beefb77765f)

It didn't fix by relaunch.

### Version

2024.718.1

### Logs

[compressed-logs.zip (The session which I got this problem)](https://github.com/user-attachments/files/16352772/compressed-logs.zip)

[compressed-logs.zip (First session after relaunch)](https://github.com/user-attachments/files/16352790/compressed-logs.zip)

**Comment by aL1NaZ4R** [comment]
Update: Folder is still unremovable after closing osu. (the red line indicated where osu has to be)
![image](https://github.com/user-attachments/assets/704a12a4-755f-4de4-a163-423eb2c17649)

**Comment by aL1NaZ4R** [comment]
Update: That got fixed by restarting the PC.

I think I found the cause. When you open one of those hitsounds (for example) and don't close the player, then "finish editing", it will behave similar until you close the player, and I think that case was similar, but I didn't leave anything open in that folder, so it's still strange for me.

**Comment by peppy** [comment]
This means you had something open in an external app. You'll have to close it first.

Maybe the flow can better explain this to the user.

**Comment by smallketchup82** [comment]
Coming from me while I was developing the first iteration of this feature, I honestly expected this issue to show up at some point. I didn't then, still don't see a need to really address this (find a fix), except for what peppy said: adding a flow (or error message) to better explain this.

Though, I think adding a sort of "recovery" flow would also be a good idea. I'm not really concerned about this issue, but I am concerned about a user experiencing something like this, not having their changes saved, then re-mounting, and having their changes overwritten (see https://github.com/peppy/osu/blob/15220f3bf4697adfdd98b0d7d53e6a9c8b616172/osu.Game/Database/RealmArchiveModelImporter.cs#L186-L187), essentially losing all of their changes. I probably should've brought this up in review but didn't notice.

Also, for anyone that stumbles upon this issue in the future, I'd probably suggest using something like https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith to find any processes using the files and killing them prior to accepting changes

**Comment by bdach** [comment]
The best ending i can see here is somehow listing which apps have the files still open, if possible. Not sure it will be without elevated permissions.
