### ISSUE TITLE
osu!taiko finishers (big dons/kats) and double inputs are broken

### ISSUE THREAD

**Issue by Midnaait** [ppy/osu#3485]
Hello, and I apologize for my english in advance, I know it's kinda bad lol.

I was testing this mode's current status on lazer, and I noticed the big notes are too strict when trying to hit them. Usually in regular osu! you have a bit of leadway to hit the finisher with both keys in order to get the bonus points, and if you fail to get the points (unless the finisher is really near of a note which is really rare to see) you don't notelock/miss the next note.

- [x] Part 1

In Lazer, it's way stricter to hit the finishers, and it notelocks you really bad when you don't hit it perfectly 
(by perfecly I mean, hitting both keys at roughly the same time), making you miss the next notes or unable to recover, even if you hit the notes at the same time they imply you to hit them, you can watch the video for an example: [Video 1](https://www.youtube.com/watch?v=J8F1yI3Hq0Y)

First attempt is how it should work, and the second attempt I tried to fail to get the bonus of a finisher, making me fail the entire section even if I hit the notes where they belong.

- [x] Part 2

A similar issue happens when you hit a normal note with both dons or both kats. it makes you miss the next note (most seen in 1/2 patterns) regardless of the situation. This does not happen in regular osu, so it should be fixed. You can observe that behaviour here: [Video 2](https://www.youtube.com/watch?v=3d-TVQ7Eojs)

Thanks for reading, and if you need further testing I'll be happy to help.

**Comment by smoogipoo** [comment]
I've fixed part 2 of this, but part 1 is weird in that I've made sure that hit windows match up perfectly to osu!stable...

**Comment by Hanamuke** [comment]
@smoogipoo Have you checked that 1 still happens ? Intuitively I would think that you fixed both problems

**Comment by smoogipoo** [comment]
I have attempted to check this, but I'm not a taiko player so I can't really reach complex scenarios like the one mentioned. A replay that demonstrates the difference would be amazing.

**Comment by Midnaait** [comment]
Oh hey, it works now, nice.
