### ISSUE TITLE
Game receives mouse event while clicking a foreground window

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3580]
When inactive the lazer window and click another window (which is front of lazer's window), lazer's window recieves click event (left click and right click)
OS: Windows 7 x64
Rev: 2018.928.0 (cause: #3550)

**Comment by smoogipoo** [comment]
Can't replicate on the latest build on either macOS or Windows. Going to assume this was fixed with the various input changes since then (particularly, `Handle()`.

**Comment by peppy** [comment]
@lolita-is-godddd how often can you reproduce this? can you confirm it still happens on the latest build?

**Comment by lolita-is-godddd** [comment]
at every time on above build. for latest, i could not install it, so i didn't verify whatever issue happens or not.

**Comment by lolita-is-godddd** [comment]
1228 still has this bug.

**Comment by peppy** [comment]
This must be win7 specific. Have never seen this happen during any testing. Can anyone else on windows 7 please confirm?

**Comment by Marcel1202** [comment]
Having the same problem with the newest release using Ubuntu 18.10.

**Comment by Joehuu** [comment]
Disable raw input and reproduction works 99.9%. On Windows 10.
To reproduce:
- Launch osu!lazer anywhere (ide/binary)
*osu!lazer window is not visible yet*
- Quickly focus to a window (say google chrome, maybe spam click for fast comps) and wait until osu!lazer appears and loads to main menu
- Clicking on window results in osu!lazer getting input

https://puu.sh/DKtnK/155d750484.mp4

Focusing osu!lazer at this point will fix this issue. This doesn't happen with raw input enabled.

**Comment by peppy** [comment]
Moving to milestone now that we have an accurate reproduction.

**Comment by bdach** [comment]
Can't seem to hit this on current `master` with the repro steps mentioned above on any of the three screen modes (raw input disabled) - wondering if I'm doing anything wrong?

**Comment by Joehuu** [comment]
Yeah... can't reproduce on master. Not sure if we want the PR that fixed this. I hate hidden fixes.

Range will be 2019.621.0 - before `master` if anyone wants to figure out what PR this fixed.

**Comment by bdach** [comment]
Performed a bisection to see what fixed this (see [bisection log](https://github.com/ppy/osu/files/3687962/bisection-log-3580.txt)) - seems to have been fixed by a framework bump (2019.830.0 → 2019.830.1), which consisted of a single PR (ppy/osu-framework#2810).

I hit a couple of revisions wherein performing the repro scenario caused a hard crash with the same stacktrace as ppy/osu-framework#2809 (example of such a revision: 80671ce), which the aforementioned PR fixed, so I think this can be safely considered closed and buried.
