### ISSUE TITLE
Song finishes but map does not

### ISSUE THREAD

**Issue by yusdacra** [ppy/osu#4095]
**Describe your problem:** So i was playing a beatmap, while installing something from JetBrains Rider. Some time before song finished, the download in Rider was completed, and unzipping made the game lag. Then, the song finished, but map didn't. I suspect that low fps can cause this? Related to #3827 ?

**Screenshots or videos showing encountered issue:** 
![map freeze](https://user-images.githubusercontent.com/19897088/51404902-dcb4e400-1b65-11e9-99e8-4b1d4c561cd3.png)
You can see that song is finished, but map still doesn't finish. And the health bar doesn't move at all.
**osu!lazer version:** 2019.117.0
**Logs:** [logs.zip](https://github.com/ppy/osu/files/2774046/logs.zip)

**Comment by peppy** [comment]
Yes, I'd wage that this issue affects all rulesets, not just taiko.

**Comment by peppy** [comment]
This generally happens when the game lags and a hitobject is not correctly set to a hit/miss state (due to lifetime being passed and `UpdateState` not being executed).

We may be able to fix this quite easily using `LifetimeManagementContainer` (see [PR](https://github.com/ppy/osu-framework/pull/2020)) cc/ @ekrctb

**Comment by daniel11420** [comment]
This happened to me on iOS once, if it helps then I was holding 4 fingers on the screen at the same time when it happened

**Comment by peppy** [comment]
May be resolved via #4102, needs confirmation.

**Comment by smoogipoo** [comment]
Fixed by referencing PRs.

**Comment by Thesola10** [comment]
Can still reproduce, 2021.320.0 on osu!mania, on this specific beatmap https://osu.ppy.sh/beatmapsets/519505#osu/1906276

Has been the case since February builds.

**Comment by bdach** [comment]
@Thesola10 I cannot reproduce this. Both autoplay and normal gameplay seems to complete here. Can you try seeing if autoplay completes, and also try to update the map (just for sanity's sake, so that we're not looking at two separate versions).

Please open a separate issue and include all the necessary details. A video might also be useful.

**Comment by Thesola10** [comment]
@bdach We were indeed looking at different versions. For my bug report, I first attempted to export the .osz as-is (from the editor) but it didn't work, so I assumed the beatmap (which was graveyarded on my end) had not been updated.

By updating (deleting, reopening osu, and re-downloading), the new map does indeed work, but that means that I have lost the version that caused the problem (which would have been useful to have for a new bug report).

Just in case, I attached the logs from the session where I couldn't finish the map (which may also contain errors from my attempt to export the osz)
[logs.zip](https://github.com/ppy/osu/files/6175308/logs.zip)

**Comment by bdach** [comment]
@Thesola10 Unfortunately, the logs you've linked do not contain any errors that might hint to the cause of this. From experience, I wouldn't expect any errors either - the cause of gameplay not completing is most often a bug that causes one of the objects to not get any judgement applied to it (whether hit or miss), and won't show up in logs.

Seeing that the original beatmap file is lost, I'm not sure there's anything to look into at this juncture (unless you're able to recover it somehow).

**Comment by Thesola10** [comment]
Update: the new map also does not seem to complete properly in mania (same difficulty) on my end...

**Comment by bdach** [comment]
Generally some way to confirm which objects might not be getting judged properly will be useful in this context. If you aren't able to produce a video, a replay might be an alternative route, but you won't be able to get one from lazer, since, well... for the replay to be created, gameplay has to end.

So if you were able to record a replay on this map on stable, which then doesn't complete in lazer, then that would be ideal in this situation.

**Comment by Thesola10** [comment]
I have re-exported the .osz of the new version from the editor, which you can find attached (renamed from osz to zip): 
[xi - over the top (Weriko).zip](https://github.com/ppy/osu/files/6175323/xi.-.over.the.top.Weriko.zip)

**Comment by bdach** [comment]
Nope, sorry. Autoplay still completes fine. As stated above already, please open a separate issue for this if you can produce any more useful information.
