### ISSUE TITLE
Autoplay fails to achieve perfect under some conditions

### ISSUE THREAD

**Issue by lithiumjs** [ppy/osu#4248]
**Describe your problem:** While watching Auto mod playing Aleph-0 beatmap, I noticed that it hits and misses some circles and gets a D-rank in the end (osu!stable had S)

**Screenshots or videos showing encountered issue:** https://youtu.be/7hs19xGz6Vs

**osu!lazer version:** 2019.131.0

**Logs:**
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2864356/performance-gamethread.draw.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2864357/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2864358/runtime.log)
[database.log](https://github.com/ppy/osu/files/2864359/database.log)
[network.log](https://github.com/ppy/osu/files/2864360/network.log)
[performance.log](https://github.com/ppy/osu/files/2864361/performance.log)

**Comment by HoLLy-HaCKeR** [comment]
This beatmap also seems to generate wrong hitobjects, likely due to extreme timing points generating more slider ticks than stable.

**Comment by peppy** [comment]
I believe this has since been resolved (please confirm if able).

**Comment by Morilli** [comment]
This does not seem to have been resolved completely. Although it seems like that lazer is trying to hit 2 circles at times where there should only be 1, so it's likely more related to beatmap parsing than autoplay.

**Comment by HerendraTJ** [comment]
This issue still happened in 2019.913.0 
Proof : https://youtu.be/Cgz87fVWhxo
Skip to 0:30

**Comment by iiSaLMaN** [comment]
> This issue still happened in 2019.913.0
> Proof : https://youtu.be/Cgz87fVWhxo
> Skip to 0:30

How is this related to the issue? we're talking about `Autoplay` missing objects, not inaccurate replays, please submit another issue about that (if there wasn't already)

**Comment by HerendraTJ** [comment]
> > This issue still happened in 2019.913.0
> > Proof : https://youtu.be/Cgz87fVWhxo
> > Skip to 0:30
> 
> How is this related to the issue? we're talking about `Autoplay` missing objects, not inaccurate replays, please submit another issue about that (if there wasn't already)

Oh sorry my bad

**Comment by PercyDan54** [comment]
This should be resolved now
![osu_2021-04-18_12-12-26](https://user-images.githubusercontent.com/50285552/115134024-5be43b80-a03f-11eb-9ab5-774ff96fcef5.jpg)

**Comment by peppy** [comment]
Seems to match close enough to stable to consider this specific report resolved.
