### ISSUE TITLE
Entering and exiting editor rapidly exits the MainMenu BackgroundScreenDefault

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4601]
**Describe the crash:** 
Quickly going into the editor and back to the menu causes the background to stay black and as soon the song ends or you switch the song the game crashes
**Screenshots or videos showing encountered issue:** 
https://streamable.com/kw2uk
**osu!lazer version:** 
Latest commit 1b7d8b7
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3050314/runtime.log)

**Computer Specifications:** 
i3 6100, GTX1050ti, 8GB Ram, Windows 10 Pro x64 1809

**Comment by iiSaLMaN** [comment]
I think that's fixed as a delay occurs when going into osu!editor

**Comment by peppy** [comment]
Unless you can point to a commit or PR fixing it, commenting you "think" it's fixed is a bit pointless.

**Comment by iiSaLMaN** [comment]
Hmm, i can't seem to find the commit or PR that fixed it, but it really is fixed

**Comment by Lolihunter1337** [comment]
@iiSaLMaN no it is not fixed. as i can still reproduce it on the latest git

**Comment by iiSaLMaN** [comment]
That's weird, but i can tell that there is a difference when trying to do that :/

**Comment by nyquillerium** [comment]
this is fixed by https://github.com/ppy/osu-framework/pull/2369
