### ISSUE TITLE
Freeze during intro sequence on Android

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6315]
**Describe the crash:** The game freezes while playing the intro sequence about 20% of the time. It happens with either sequence.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/i7e3h

**osu!lazer version:** 0.1 / 2019.925.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3666500/runtime.log)
[network.log](https://github.com/ppy/osu/files/3666501/network.log)
[performance.log](https://github.com/ppy/osu/files/3666502/performance.log)
[database.log](https://github.com/ppy/osu/files/3666503/database.log)

**Computer Specifications:** Nokia 7 Plus, Android One (9)

**Comment by bdach** [comment]
Unfortunately nothing interesting in the attached logs. Is the freeze permanent, as in the game doesn't ever continue?

**Comment by smileyhead** [comment]
Yes.

**Comment by MeguMario** [comment]
As in my test, there is a small chance that it will freeze, just reopen the game and it will be fine

**Comment by miterosan** [comment]
The relevant line is: 

``
2019-09-29 08:12:13: Could not load rulesets from directory /
``

**Comment by bdach** [comment]
I'm not actually convinced that is a fatal failure (although it may warrant looking into). Refer to #6311 for an example of a mobile issue wherein the same line appears but the game does indeed continue past the intro.

**Comment by miterosan** [comment]
I suspect that the problem described here is that the current directory cannot be read or written to.

**Comment by miterosan** [comment]
I suspect that the crash in #6311 may have a different source.

**Comment by bdach** [comment]
> I suspect that the problem described here is that the current directory cannot be read or written to.

Well, seeing that `Environment.CurrentDirectory` is [guaranteed to return an absolute path](https://docs.microsoft.com/en-us/dotnet/api/system.environment.currentdirectory?view=netframework-4.8), and it's returned the root dir `/`, I'd say you'd be correct on this one.

**Comment by bdach** [comment]
Today's release (2019.1011.0) has introduced additional log output that aims to find the root cause of this issue. Please check if the problem still persists and upload fresh logs if it does.

**Comment by smileyhead** [comment]
Got it to happen again after about 7-8 tries.
[database.log](https://github.com/ppy/osu/files/3718851/database.log)
[network.log](https://github.com/ppy/osu/files/3718852/network.log)
[performance.log](https://github.com/ppy/osu/files/3718853/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3718854/runtime.log)

**Comment by bdach** [comment]
Well, I can see the access violation in `/`, as expected, but I'm still not convinced it's the actual cause. You've mentioned that the crash doesn't happen every run, mind attaching logs when the game *doesn't* crash so that we can compare the two?

**Comment by smileyhead** [comment]
Sure.
[database.log](https://github.com/ppy/osu/files/3718930/database.log)
[network.log](https://github.com/ppy/osu/files/3718931/network.log)
[performance.log](https://github.com/ppy/osu/files/3718932/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3718933/runtime.log)

**Comment by Squigglz** [comment]
Im on IOS and my fame just keeps freezing during a song.

**Comment by smileyhead** [comment]
@Squigglz Youur problem isn't related to this issue, but [several people](https://github.com/ppy/osu/issues?q=is%3Aissue+ios+freeze+is%3Aclosed) seem to have had gameplay freeze issues on iOS. Since all of their issues seem to have been resolved with a performance update, try getting the latest version if you haven't already, and if that doesn't work, open a new issue.

**Comment by bdach** [comment]
Going back on topic: in both cases (with or without freeze) the ruleset loading error persists, so it seems it is unrelated to the crash. However a noticeable difference seems to be the intro choice (freezes on `IntroCircles`, no freeze on `IntroTriangles`).

I'm assuming you have random intro choice enabled. Did you ever get an instance of launching without a freeze with the circle intro? Does going to triangles-only prevent them from happening?

**Comment by smileyhead** [comment]
> Did you ever get an instance of launching without a freeze with the circle intro?
Yes, the intro only freezes about 20% of the time.
> Does going to triangles-only prevent them from happening?
Now that you mention it, I don't recall Triangles ever freezing.

**Comment by bdach** [comment]
@smileyhead Can you check if this has been resolved in the newest versions? We've deployed a fix for other hangs recently, so it's possible this also ended up being fixed along the way.

**Comment by smileyhead** [comment]
I've tested it 20 times & had no crashes!

**Comment by bdach** [comment]
Great to hear! I'll close this for now, hopefully for good - if you get it to happen again please let us know.
