### ISSUE TITLE
Game freezes (without crash) during gameplay on mobile devices

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#6355]
After updating to **2019.930.0**, osu!lazer begins to freeze again. Just like what happened to previous issue, it could be related to `Xamarin`.

**Current State:** _Somewhat freezes in latest release **(2020.215.0)**._
**Images:**
![51FE01C6-760B-489F-9B3C-F8DBB624C5B6](https://user-images.githubusercontent.com/48611569/65991988-8b2a5c00-e44b-11e9-84f6-0b7a02af8de3.png)
![AAFB849C-156B-43AC-A353-2230B9D9DEEB](https://user-images.githubusercontent.com/48611569/65991989-8b2a5c00-e44b-11e9-86e9-9601ead389c7.png)

**Comment by ThatsNiceGuy** [comment]
Can confirm, this has been happening throughout the day for me
iPad Pro 11” running iPadOS 13.1.2 public stable release

**Comment by dscnnctd** [comment]
#5818

**Comment by smoogipoo** [comment]
I can't seem to replicate this on a local debug build (netcore 3.0 sdk / mono 6.0.0)

**Comment by peppy** [comment]
As per last time, will update the build chain and see how that copes. More importantly than .net core or mono version is xamarin.ios version (@smoogipoo please include what you tested for reference).

Also if trying to repro you should be on release, not debug. Optimisations matter a lot in these cases.

**Comment by smoogipoo** [comment]
Xamarin.iOS
Version: 12.14.0.114 (Visual Studio Community)

Seems like a fairly old build, I'll try to test again after update.

**Comment by dscnnctd** [comment]
Still occurs in latest version **2019.1011.0**.

**Comment by peppy** [comment]
Yes, we are aware it is not fixed yet.

**Comment by BastianInuk** [comment]
This happens for me on launch, custom build, latest Xamarin, latest stable iOS.

**Comment by BastianInuk** [comment]
Latest git causes my iPhone XS to crash, can't check iOS version, as I can't bypass the app. Can't shutdown the system, idk why, the power slider won't display. Am stuck with a completely black screen.

**Comment by peppy** [comment]
Please google instructions on rebooting your phone.

**Comment by BastianInuk** [comment]
When sidebutton+volume up (or down) doesn’t react, and that’s the only thing google instructs, then there’s really not much to do besides waiting and hoping.

**Comment by swoolcock** [comment]
Took me exactly one Google search:
https://www.macrumors.com/how-to/force-restart-iphone-11-iphone-11-pro-max/

Same process applies to iPhone XS.

**Comment by BastianInuk** [comment]
Didn't see the section to force turn off the phone. Doesn't change the fact that Osu!Lazer soft-bricked (for a lack of better term) my phone, and I'd like to know how to troubleshoot why, so I can help fix this issue!

**Comment by peppy** [comment]
You will need to debug and investigate.

**Comment by ThatsNiceGuy** [comment]
Not sure about others, but lazer 2019.1213.0 hasn’t frozen once for me today.

**Comment by ThatsNiceGuy** [comment]
I take back my statement, freezes are much less often though.

**Comment by dscnnctd** [comment]
>I take back my statement, freezes are much less often though.

@ThatsNiceGuy 
It will still occur if you keep on playing longer in the app when playing multiple beatmaps. I’m still waiting for 2 months to get the fix as much as you do.

**Comment by ThatsNiceGuy** [comment]
Now is very often on iOS and due to the new TestFlight link I can’t rollback to a version to where it didn’t happen.
Lazer 2019.1219.0

**Comment by dscnnctd** [comment]
>Now is very often on iOS and due to the new TestFlight link I can’t rollback to a version to where it didn’t happen. ...

@ThatsNiceGuy did you mean previous versions before chaotic actions caused by `Xamarin.iOS`? I’ve been experiencing this when this bug is reintroduced and is still there up until _latest_.

**Comment by ThatsNiceGuy** [comment]
Yes, by “previous versions” I mean builds before October. I had been using a build from September so it wouldn’t crash all the time

**Comment by bdach** [comment]
There was a suggestion made at #7375 about how this might occur when break time starts - can anyone else confirm if that's the particular scenario freezes occur at, or are they essentially random?

**Comment by xTerraUWU** [comment]
It also occurs randomly too sometimes for me, but for the most part if I ever get freezes it’s on certain beat maps that I play

**Comment by ThatsNiceGuy** [comment]
it seems to occur randomly for me but more when the game is doing something that would stress the system like huge concentrations of notes and stuff like that

**Comment by peppy** [comment]
I believe this is going to be GC related. I had a similar issue with another iOS project under xamarin and it turned out to be incorrect freeing or native memory.

Next step would be reproducing with debug available.

**Comment by dscnnctd** [comment]
Closing as this has been resolved in latest February builds.

**Comment by peppy** [comment]
Awesome!

**Comment by ThatsNiceGuy** [comment]
Sorry to be a bearer of bad news but this still happens on the osu! ruleset (not mania, taiko or ctb) on the latest 2020.215.0 release on TestFlight.

Device: iPhone XR 128GB
osu!supporter TestFlight link

**Comment by peppy** [comment]
Can you reliably reproduce? Specific beatmap? How long until reproduction?

**Comment by dscnnctd** [comment]
>Sorry to be a bearer of bad news but this still happens on the osu! ruleset (not mania, taiko or ctb) on the latest 2020.215.0 release on TestFlight. ...

@ThatsNiceGuy - weird, I’ve been running this game for 30 minutes without any issues whatsoever...

**Comment by xTerraUWU** [comment]
Yeah it still happens aswell to me running on iPhone 8 Plus 64GB. Used TestFlight link.

**Comment by ThatsNiceGuy** [comment]
Earlier today I got it to freeze on this map:
https://osu.ppy.sh/beatmapsets/122390#osu/313050
on Lunatic difficulty with storyboard off.
Happened upon tapping the first note of the song.
As the person above me said, it seemingly happens at random (no storyboard should be fine, memory usage wise) but it does happen consistently when the game is running out of memory on osu!standard maps with storyboard enabled.

**Comment by xTerraUWU** [comment]
It freezes for me on that map too. For me it loves to freeze on break times for basically all beatmap

**Comment by smoogipoo** [comment]
I'm able to replicate this and will take a quick look into it.

**Comment by smoogipoo** [comment]
Investigated this a bit further and this is the best I could come up with: https://github.com/mono/mono/issues/18925

Seems to be a low-level mono issue as far as I can tell.

**Comment by ojh050118** [comment]
The problem seems to happen occasionally on Android devices.

**Comment by dscnnctd** [comment]
>The problem seems to happen occasionally on Android devices. ...

@ojh050118 
Can you confirm this also occurs in your device?

**Comment by smoogipoo** [comment]
Further discussions on the issue: https://github.com/mono/mono/issues/18973

**Comment by myaccountgotdeleted** [comment]
Can confirm this still happens on both of my iOS devices (iPad 7th gen 128gb) and (iPhone XS Max 64gb)

- You have to restart the app by opening the app switcher and swiping osu! up and then restarting it.
- It is very common, and it happens at least once every ~5 minutes for me.

_Just wanted to let you know :)_

**Comment by ThatsNiceGuy** [comment]
Nice! I can test on some devices when this commit is included in a build submitted TestFlight
