### ISSUE TITLE
Incorrect track adjustment for some mods when exiting PlayerLoader

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6914]
**Describe the bug:** Similar to #6298, mods like Nightcore or WindUp/WindDown have the pitch level reset when exiting the PlayerLoader.

**Screenshots or videos showing encountered issue:** https://streamable.com/46huj

**osu!lazer version:** 2019.1113.0

**Comment by peppy** [comment]
Have you tested on master? This should already be resolved.

**Comment by Gabixel** [comment]
Just tested on latest master (2019.1122.0): https://streamable.com/4wwg0. Still happens.
