### ISSUE TITLE
osu exception when you change and start the beatmap/diff really fast

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7504]
**Screenshots or videos showing encountered issue:**
 https://streamable.com/rd0xe

**osu!lazer version:**
 2020.112.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4049838/runtime.log)

**Comment by peppy** [comment]
How are you triggering this? Can you tell us which keys / buttons and in which order you are pressing?

**Comment by mouzedrift** [comment]
i used mouse 1 to change the difficulty and then pressed <kbd>enter</kbd> to rapidly start the beatmap. heres a short [video](https://streamable.com/4mxjo) with input visualization.

**Comment by peppy** [comment]
Are you able to reproduce using only keyboard input (arrow keys and enter)?

**Comment by mouzedrift** [comment]
nope, mouse only doesnt work either it seems. i can only reproduce this with mouse and key input.

**Comment by peppy** [comment]
Thanks, was able to reproduce using video frames.

**Comment by peppy** [comment]
I've pushed a fix PR. If you have a local checkout please give it a shot (pretty confident it's fixed, though).

**Comment by mouzedrift** [comment]
this didnt fix it for me, im now getting a crash instead of an exception. i'll attach some logs but i doubt that they will help.

[network.log](https://github.com/ppy/osu/files/4113484/network.log)
[performance.log](https://github.com/ppy/osu/files/4113485/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4113486/runtime.log)

**Comment by peppy** [comment]
I do t think you're on the correct branch. Also your log file doesn't show any exceptions.

**Comment by mouzedrift** [comment]
> I don't think you're on the correct branch.

im on the correct branch (assuming #7623 is the right one).

> Also your log file doesn't show any exceptions.

thats why i doubt that the logs are gonna help.

**Comment by peppy** [comment]
How are you running the game? There should be error output somewhere.

**Comment by mouzedrift** [comment]
im running the game with ``dotnet run --project osu.Desktop -c Debug``

**Comment by peppy** [comment]
An error should appear in the console on crash, in that case.

**Comment by mouzedrift** [comment]
the thing is that the game starts freezing and then crashes after 1 min or so but theres nothing appearing in the console
