### ISSUE TITLE
Video decoder null reference exception on startup

### ISSUE THREAD

**Issue by seanwu1105** [ppy/osu#7947]
**Describe the crash:** 
The OSU program crashes on initialization with the following error messages.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Graphics.Video.VideoDecoder.GetConversionMatrix()
   at osu.Framework.Graphics.Video.VideoSprite.get_ConversionMatrix()
   at osu.Framework.Graphics.Video.VideoSpriteDrawNode..ctor(VideoSprite source)
   at osu.Framework.Graphics.Video.VideoSprite.CreateDrawNode()
   at osu.Framework.Graphics.Drawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
   at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass93_0.<handleException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.handleInput()
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.GameWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Desktop/Program.cs:line 57
Aborted (core dumped)
```

It seems to be related to [this PR](https://github.com/ppy/osu-framework/pull/3019) since the bug does not exist before #7935 `update-framework`.

**osu!lazer version:** 
Commits after 000787a766582bd43fae3464908bcb05e3385b36.

**Computer Specifications:** 
* Ubuntu 18.04.4 LTS
* Memory 15.6 GB
* Processor Intel Core i7-4720HQ
* Graphics GeForce GTX 965M

**Comment by peppy** [comment]
Please try installing ffmpeg

**Comment by seanwu1105** [comment]
ffmpeg `3.4.6-0ubuntu0.18.04.1` is installed

**Comment by inalone** [comment]
I'm getting this error as well
```
  ~ ffmpeg -version
ffmpeg version 4.1.4-1build2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
```

**Comment by clay53** [comment]
Also having this problem with ffmpeg installed: ```ffmpeg -version
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
```

**Comment by huupoke12** [comment]
Maybe related to the ffmpeg version. I'm running Arch Linux with ffmpeg 4.2.2 and do not have this issue.

**Comment by bdach** [comment]
Can reproduce, investigating.

**Comment by bdach** [comment]
While this crash should be better-handled framework-side, at least in my case it turned out that one of the issues was a missing `libavformat.so`. Therefore for the time being you could try to install the distribution-appropriate packages containing `libavformat`.

Confirmation that this is the case for you can be obtained by examining runtime logs (should have an entry about missing libraries right before the crash stack) or passing `LD_DEBUG=libs`.

For example, on my xenial 16.04, the following seems to alleviate crashes:
```
$ sudo apt-get install libavformat-ffmpeg56
```

**Comment by Wello6143** [comment]
> Maybe related to the ffmpeg version. I'm running Arch Linux with ffmpeg 4.2.2 and do not have this issue.

I have the same version of ffmpeg with you on openSUSE Tumbleweed but it still crashes.

**Comment by Jajcus** [comment]
Looks like osu! wants to open 'libavformat.so' which is a symlink which should be only used for linking while building software and is included in development packages only (libavformat-dev in Ubuntu) and won't be normally installed on an end-user computer.
On runtime a specific soname should be used, like 'libavformat.so.58' for the version included in Mint 19.3 / Ubuntu bionic.

Installing the 'libavformat-dev' package in Ubuntu is a working workaround for me, but this should not be needed.

**Comment by bdach** [comment]
@Jajcus See #7963, in particular [this comment](https://github.com/ppy/osu/issues/7963#issuecomment-589978238). If there is a bundlable LGPL-licensed ffmpeg binary package that will work cross-distro, we could consider bundling it.

**Comment by bydavenet** [comment]
Installing `libavformat-dev` via apt fixes issue for me too on my Pop!_OS 19.10 which is Ubuntu based.

**Comment by bdach** [comment]
Temporarily reopening until next framework bump & release due to number of incoming duplicates to hopefully aid visibility and avoid getting more.

**Comment by iiSaLMaN** [comment]
This should be fixed now on [2020.225.0](https://github.com/ppy/osu/releases/tag/2020.225.0), can be closed.

**Comment by TechAdvancedCyborg** [comment]
And this is still an issue for Ubuntu 20.04 with libavformat58...

**Comment by bdach** [comment]
@TechAdvancedCyborg We are aware that linux distros that don't bundle ffmpeg 4 in their package lists will run into issues with video playback (see the aforementioned issue at #7963). It however should not be crashing.

Unless you are actually experiencing crashes please refrain from posting such comments as they are not helpful. Fixing the library issue is not a top priority right now and we have limited bandwidth.

**Comment by TechAdvancedCyborg** [comment]
It's a very similar error message but not due to the same reasons, the issue I'm experiencing is from osu! frame stability counter, it just crashes on launch >50% of the time only on Linux

**Comment by bdach** [comment]
If you expect the problem to be resolved then please post the actual error message and as many other pertinent details as you can think of, preferably in a new issue. The information you have provided thus far is not actionable.
