### ISSUE TITLE
Editor Timeline throws exceptions for extremely short beatmaps

### ISSUE THREAD

**Issue by Alchyr** [ppy/osu#8742]
Exception occurs in load method of Timeline.

When a Beatmap with a track length less than 10 seconds is loaded, MinZoom will throw an argument exception due to attempting to set it to a value less than 1.

**Comment by smoogipoo** [comment]
This was already fixed in https://github.com/ppy/osu/pull/8695

**Comment by Alchyr** [comment]
oops

**Comment by bdach** [comment]
For long beatmaps sure, but short ones? Any track <500ms should still throw from what I'm seeing, right?

**Comment by bdach** [comment]
I just tested and short tracks do throw. Here's a repro map: [short - map.osz.zip](https://github.com/ppy/osu/files/4469444/short.-.map.osz.zip)

**Comment by smoogipoo** [comment]
Granted a 500ms map shouldn't exist but yeah this does need a more failsafe solution - probably doing the bounds checking lazily.
