### ISSUE TITLE
Possible memory leak 

### ISSUE THREAD

**Issue by enricoKoschel** [ppy/osu#9049]
**Describe the bug:** 
After about 2 hours of gameplay, the ram usage went up to over 7 GB(I have 16 GB). This also caused stuttering every few minutes for a few second. After a game restart, I tried replicating the behavior and found out, that every time a new Beatmap is selected in the menu, RAM usage goes up by up to 30 MB.

**Screenshots or videos showing encountered issue:** 
RAM and statistics at game start
![ram after start](https://user-images.githubusercontent.com/10744823/82158204-b81a6a80-9886-11ea-9955-b6fcf3006686.png)
![statistics after start](https://user-images.githubusercontent.com/10744823/82158207-b8b30100-9886-11ea-9c98-a498a8aa8ce5.png)

RAM and statistics after selecting random maps for 5 minutes
![ram after 5 min](https://user-images.githubusercontent.com/10744823/82158205-b8b30100-9886-11ea-9b80-41d3af0457f3.png)
![statistics after 5 min](https://user-images.githubusercontent.com/10744823/82158208-b94b9780-9886-11ea-83ae-68941453f0e2.png)

Error messages
![errors](https://user-images.githubusercontent.com/10744823/82158203-b781d400-9886-11ea-90c9-b6d8c697541c.png)

**osu!lazer version:** 
2020.515.0

**Logs:**

[performance.log](https://github.com/ppy/osu/files/4640881/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4640882/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4640883/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4640884/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4640885/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4640886/updater.log)
[database.log](https://github.com/ppy/osu/files/4640887/database.log)
[network.log](https://github.com/ppy/osu/files/4640888/network.log)

**Comment by peppy** [comment]
Would have been useful to see the lower sections of global statistics.

Did you try going back to the main menu and clicking "clear all caches" in settings?

**Comment by smoogipoo** [comment]
This is a duplicate of https://github.com/ppy/osu/issues/8992

Definitely looks like there's something wrong here.

**Comment by enricoKoschel** [comment]
I didn't realize you can scroll the statistics. Here are all of them. I also tried pressing "clear all caches", it cleared a few hundred MBs of RAM and clicking it again did nothing.
![1](https://user-images.githubusercontent.com/10744823/82214899-cb751680-9916-11ea-85d6-8b5b2fe11fb6.png)
![2](https://user-images.githubusercontent.com/10744823/82214902-cb751680-9916-11ea-86fd-b7321544ebe6.png)
![3](https://user-images.githubusercontent.com/10744823/82214904-cca64380-9916-11ea-840b-973fa58f6dbf.png)
![4](https://user-images.githubusercontent.com/10744823/82214896-ca43e980-9916-11ea-8fe0-f53bc1c1824b.png)

**Comment by MTGPROD** [comment]
This is why on android after 30 minutes of gameplay the game start have lag spikes?

**Comment by peppy** [comment]
@enricoKoschel Could you please check this has been fixed in the latest release?

**Comment by enricoKoschel** [comment]
Checked on 2020.602.0:
RAM usage still goes up, but definitely slower than before. After about 5 minutes of selecting random songs, it went up to about 2 GB. 
These errors do still appear though:
![errors](https://user-images.githubusercontent.com/10744823/83584255-d949af00-a546-11ea-85e6-40d728e290ab.png)

**Comment by peppy** [comment]
Those errors look fine for now.

Still going up is to be expected, but it shouldn't go up forever as previously. Also, exiting to the main menu should recover memory usage somewhat.

**Comment by enricoKoschel** [comment]
Going to the main menu brought memory usage down to about 1.5 GB consistently.

**Comment by peppy** [comment]
Great to hear. Going to close this for now. The remaining high memory issues will be addressed going forward as we move more systems to use pooling (and potentially rewrite the carousel to be less weird).

**Comment by VirgilFabre** [comment]
So I was programming, when I noticed something odd.
I was talking in the chat once in a while, when I noticed Osu! was consuming 7GB of ram!
It has been up for ~4 hours but still. Memory leak confirmed.
![memory_leak](https://user-images.githubusercontent.com/40531871/85538147-99746580-b5e2-11ea-89f9-d154df9f3f67.png)

**Comment by bdach** [comment]
Saying "memory leak confirmed" is not helpful on its own. Any details on what you were doing for those 4 hours? Memory snapshots, profiling results, anything?

At this point one of us is likely going to have to run a stress test overnight or something since reports keep popping up without much substance.

**Comment by peppy** [comment]
High memory usage does not necessarily point to a memory leak. If you are a developer, you should be reading the issue you're posting in and post required information / logs to actually be useful.

Please avoid posting such pointless posts in the future.

**Comment by VirgilFabre** [comment]
I have no idea on how to get the logs you need, I'm just confirming there's a leak.
No need to be like this...

**Comment by VirgilFabre** [comment]
I posted everything I knew. There is indeed a memory leak, I was only chatting, if you want logs ask me I'll have them, unless they are destroyed once lazer reload, because when I noticed it was leaking when I printscreen lazer crashed when I came back.
