### ISSUE TITLE
Linux release does not have an icon set

### ISSUE THREAD

**Issue by SS-035** [ppy/osu#9913]
**Describe the bug:** 
I have no application icon in the Ubuntu 20.04 side panel for OSU!lazer running as shown the attached screenshot. I don't know if it is related not not but I had "accidentally" deleted the `~/.local/share/icons/` folder. Also running the appimage in the terminal shows the following output.
```
touch: cannot touch '/home/user/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
```
If it is due to my misdoing then how can I fix that?

**Screenshots or videos showing encountered issue:** 
![pic](https://user-images.githubusercontent.com/56174018/90612074-2aec0680-e225-11ea-84bd-65b2e54d13ef.png)

**osu!lazer version:** 
2020.814.0.0

**Comment by smoogipoo** [comment]
Sounds like you need to make sure that directory exists. This is completely on you to figure out if that doesn't work - this isn't tech support to revert the actions you've done to your system.

**Comment by SS-035** [comment]
Well, I told that me deleting the `~/.local/share/icons/` folder could be the source of the problem but apparently it was not. 

Below here is the same problem when appImage running fresh in a lubuntu OS.
![lubuntu pic](https://user-images.githubusercontent.com/56174018/90622249-7a84ff00-e232-11ea-827d-620af1484134.png)
 

Same problem in another fresh ubuntu 20.04.
![ubuntu pic](https://user-images.githubusercontent.com/56174018/90622390-a902da00-e232-11ea-8b88-9643a3d2b640.png)

**Comment by huupoke12** [comment]
Maybe the a clean Ubuntu installation doesn't create that folder by default, try `mkdir -p ~/.local/share/icons/hicolor`.

**Comment by SS-035** [comment]
I have already tried that. The terminal output of `touch: ...` is no longer there, but there is still no icon in the panel.

**Comment by smoogipoo** [comment]
Hmm I've just tried to replicate myself and don't get the icon either, instead the default xfce icon. Perhaps we need to set an icon for the appimage somehow?

Will reopen.

**Comment by smoogipoo** [comment]
Or... We just need to set the window icon, which we only do for the windows window at the moment. As far as I can tell we need to use https://wiki.libsdl.org/SDL_SetWindowIcon.

**Comment by Joehuu** [comment]
Fixed in SDL after https://github.com/ppy/osu/pull/10297.

**Comment by ggliv** [comment]
Tested the latest build (2020.1020.0) on two of my Linux machines, both running XFCE on Debian 10. The icon is still missing. No errors in terminal.

![Screenshot 1](https://user-images.githubusercontent.com/47010459/96610567-c5220680-12c9-11eb-8b05-2acf0b01aabf.png)
![Screenshot 2](https://user-images.githubusercontent.com/47010459/96611356-92c4d900-12ca-11eb-9758-877c81834b59.png)

**Comment by bdach** [comment]
@ggliv are you sure you're running with the `--sdl` command line argument?

**Comment by ggliv** [comment]
Gosh, no I wasn't. Sorry for the confusion. Everything looks good!

**Comment by acedron** [comment]
Tried it with `--sdl` argument in 2020.1020.0 build with GNOME 3.38.1 on Xorg on Arch Linux. The icon is still missing.

**Comment by bdach** [comment]
@acedron what am I looking at in the attached picture? is that a desktop icon or a taskbar one? if the former we're likely not doing whatever the proper incantation is to get linux WMs to display a proper icon if the app is not open. it should however be working when the game is open (in taskbar/<kbd>Alt</kbd>-<kbd>Tab</kbd> menu).

**Comment by acedron** [comment]
@bdach Sorry forgot to mention. It was a taskbar. Here is a screenshot of taskbar, while game is open.

![image](https://user-images.githubusercontent.com/45771313/97118926-efd2eb80-171d-11eb-9115-0cd8363463f2.png)

**Comment by Joehuu** [comment]
@acedron can you see if the icon is shown now in the latest release?

Fixed in SDL for me as of now (using Ubuntu).

**Comment by acedron** [comment]
@Joehuu yes it seems like it is fixed now for me too.

![image](https://user-images.githubusercontent.com/45771313/101131071-bf804600-3615-11eb-9db1-5e0243797780.png)

**Comment by Joehuu** [comment]
Closing as resolved.
