### ISSUE TITLE
Buttons suddenly not working properly 

### ISSUE THREAD

**Issue by Arzhiel** [ppy/osu#9996]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/70353668/91508442-b9394a00-e901-11ea-9330-b38e9a447972.gif)
When i was playing, the buttons suddenly stopped working (I'm playing on android). The circles would miss even though i clicked. After that, i went back but couldn't press any buttons like settings or osu direct. I was multi tapping the screen on the break countdown because i forgot we still can't multi tap and the whole game wouldn't respond to tapping afterwards.

**Comment by peppy** [comment]
Bumping this up in priority as multiple people can confirm this (multitouching causes all further touches to fail).

**Comment by peppy** [comment]
This was resolved already.

**Comment by Aksumxd** [comment]
i'm still experiencing this on the latest release.

Tapping multiple fingers on the screen causes B1 to be pressed down permanently. Doesn't happen with 2 fingers, but pressing 3 fingers or more simultaneously causes it to lock up
Sometimes spamming the screen solves the issue (releases B1 from being stuck)

Oneplus 5 A5000, Android 10

https://user-images.githubusercontent.com/63202855/166435919-9afb8c1b-61ed-4264-bd5b-2b5e116f7299.mp4

**Comment by peppy** [comment]
What version of lazer are you running?

**Comment by Susko3** [comment]
@Aksumxd could you do the following:

- get the click stuck (press three fingers on the screen)
- move away all the fingers from the screen
- one by one, tap four fingers on the screen
  - at first, tap only one, then, keep it on the screen, and tap the next finger, etc.
- is the click still stuck after this?

**Comment by Aksumxd** [comment]
I am running 2022.501.0

@Susko3 the click gets released after doing the steps you mentioned:

https://user-images.githubusercontent.com/63202855/166480680-40ec1fae-164b-45b4-a613-9267806aa836.mp4

I should also mention that just like the original poster mentioned, I am unable to click anything in the game while B1 is stuck (menu buttons such as retry, back etc. so not just hit-circles)

**Comment by Susko3** [comment]
The phone's swipe three fingers gesture to take a screenshot (even if a screenshot is not triggered) is interfering with osu!framework touch handling.

I can repro this on my phone (Realme 6), but I've not investigated much. Probably related to never getting the touch up event for one (or more) of the fingers used in the gesture.

Two touches stuck after tapping three fingers on the screen:

![Screenshot_2022-05-03-17-37-14-03_fca46a2731136e673b8638a972bc0192](https://user-images.githubusercontent.com/16479013/166486314-e4666965-98d0-4a8a-84ea-8fefe7412082.jpg)


Draging with one finger after that:

![Screenshot_2022-05-03-17-37-19-18_fca46a2731136e673b8638a972bc0192](https://user-images.githubusercontent.com/16479013/166486366-7c47b04a-b36f-4791-a90a-f1bcea293cc2.jpg)

**Comment by frenzibyte** [comment]
I'm not entirely sure how the gesture is intercepting the touch event from the view, but from a quick googling through stack overflow, I've came across [this thread](https://stackoverflow.com/a/52305274) which may or may not be valid in this case, but maybe worth a try.

As per the thread, wondering what happens if you try moving handling the touch event from `View.Touch` to `AndroidGameActivity.DispatchTouchEvent`.
